/gate/world/daughters/name phbkg
/gate/world/daughters/insert box
/gate/phbkg/geometry/setXLength 140 mm
/gate/phbkg/geometry/setYLength 200 mm
/gate/phbkg/geometry/setZLength 300 mm

# Coordinate is a world, not a phantom
# Phantom X Start:
# -3+2 : fanbeam x edge left
# Offset (scan start offset = -15 mm from the phantom center) --> phantom moves +15 (opposite direction)
# (-3+2+15-140/2) ~ (-3+2+15-140/2 + 140)
# 14

/gate/phbkg/placement/setTranslation 14 0 321 mm	# ZStart (default) for 50mmH Grid -> 136+30 = 166, 166+5+0~166+5+70
							# (166 + 5mm margin) ~ (166+5+300) / 2
/gate/phbkg/setMaterial  Soil_d06			# Air, Soil, Soil_soft, Soil_soft_v3
/gate/phbkg/vis/forceWireframe
/gate/phbkg/vis/setColor grey


# From here, Coordinate is a phantom, not a world
#######################################################################################################> Pos 1
#======================================================== 30 mm depth@center slice of hand
/gate/phbkg/daughters/name handstl
/gate/phbkg/daughters/insert tessellated
/gate/handstl/geometry/setPathToSTLFile 		mac/phantoms/hand_stl_files/right-human-skeleton-150mm.stl
/gate/handstl/setMaterial Hand_bones_spongiosa	# Hand_bones_spongiosa, Femora_sponsisa, CorticalBone, Polyethylene
/gate/handstl/vis/forceSolid
/gate/handstl/vis/setColor yellow
#/gate/handstl/placement/setRotationAxis 0 1 0
#/gate/handstl/placement/setRotationAngle -90 deg
/gate/handstl/placement/setRotationAxis 1 0 0
/gate/handstl/placement/setRotationAngle -90 deg
#/gate/handstl/placement/setTranslation  -90 -75 -58 mm  # -58: backhand edge(emd)
#/gate/handstl/placement/setTranslation  -180 -75 -93 mm  # -93: fronthand edge(qkekr) 90mmW, 150mmL, 35mmT
####################################################################
# Z center of handstl is -58-93/2 = -75.5 (0mm)
# and then we will bury it under 40mm depth
# Z: -75.5+40 = -35.5(x) --> -75.5+30 = -45.5
# Y: center is -75
# X: start point is -90... and the we have to scan it 100seconds...
####################################################################
/gate/handstl/placement/setTranslation  -90 -75 -45.5 mm  # (90mmW, 150mmL, 35mmT)

#======================================================== 0~10 mm depth  ==> upper foreign insert
/gate/phbkg/daughters/name fi_rock_boxes_up
/gate/phbkg/daughters/insert box
/gate/fi_rock_boxes_up/geometry/setXLength 10 mm
/gate/fi_rock_boxes_up/geometry/setYLength 10 mm
/gate/fi_rock_boxes_up/geometry/setZLength 10 mm	
/gate/fi_rock_boxes_up/placement/setTranslation 0 0 -145 mm  # Z: (-150+0) ~ (-150+0+10)/2
							# X: -50~-40/2
/gate/fi_rock_boxes_up/setMaterial Rock		# Hand_bones_spongiosa, Femora_sponsisa, CorticalBone, Polyethylene
/gate/fi_rock_boxes_up/vis/forceSolid
/gate/fi_rock_boxes_up/vis/setColor blue

/gate/fi_rock_boxes_up/repeaters/insert cubicArray
/gate/fi_rock_boxes_up/cubicArray/setRepeatNumberX 	8
/gate/fi_rock_boxes_up/cubicArray/setRepeatNumberY 	12
/gate/fi_rock_boxes_up/cubicArray/setRepeatNumberZ   	1
/gate/fi_rock_boxes_up/cubicArray/setRepeatVector 	15 	15 	0 mm
/gate/fi_rock_boxes_up/cubicArray/autoCenter true

#======================================================== 50~60 mm depth  ==> upper foreign insert
/gate/phbkg/daughters/name fi_rock_boxes_bottom
/gate/phbkg/daughters/insert box
/gate/fi_rock_boxes_bottom/geometry/setXLength 10 mm
/gate/fi_rock_boxes_bottom/geometry/setYLength 10 mm
/gate/fi_rock_boxes_bottom/geometry/setZLength 10 mm	
/gate/fi_rock_boxes_bottom/placement/setTranslation 0 0 -95 mm  # Z: (-150+50) ~ (-150+50+10)/2
							# X: -50~-40/2
/gate/fi_rock_boxes_bottom/setMaterial Rock		# Hand_bones_spongiosa, Femora_sponsisa, CorticalBone, Polyethylene
/gate/fi_rock_boxes_bottom/vis/forceSolid
/gate/fi_rock_boxes_bottom/vis/setColor magenta

/gate/fi_rock_boxes_bottom/repeaters/insert cubicArray
/gate/fi_rock_boxes_bottom/cubicArray/setRepeatNumberX 	8
/gate/fi_rock_boxes_bottom/cubicArray/setRepeatNumberY 	12
/gate/fi_rock_boxes_bottom/cubicArray/setRepeatNumberZ   	1
/gate/fi_rock_boxes_bottom/cubicArray/setRepeatVector 	15 	15 	0 mm
/gate/fi_rock_boxes_bottom/cubicArray/autoCenter true
